server:
  port: 8081
#  yml多配置文件定义
#激活方式:
#  方式1:命令行:在envoriment的program argument中写   --spring.profiles.active=dev   或者运行jar时加上--spring.profiles.active=dev
#  方式2:  在配置文件中指定:  spring.profiles.active=dev
#  方式3:VM options中   写-Dspring.profiles.active=dev
#spring:
#    profiles:
#      active: prod
---

#
#person:
#    lastname: zhangsan
#    age: 17
#    boss: false
#    birth: 2001/03/23
#    maps: {k1: v1,k2: v2}
#    list:
#      - lisi
#      - zhaoliu
#    dog:
#      name: xiaogou
#      age: 2
spring:
  profiles:
    active: dev
---
server:
  port: 8081
spring:
  profiles:
    active: prod