spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.106:3306/test?characterEncoding=utf8&serverTimezone=GMT&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

     
#    可以使用schema来指定位置
#    schema:
#      - classpath:department.sql